#!/bin/bash

set -e
cd "$(dirname $0)/.."

for path in Icons/*; do
  name="$(basename "$path")"
  stem="${name%%.*}"
  if [ "$stem" != "AppIcon" ] && [ "$stem" != "AppIconRounded" ]; then
    inkscape -o "The Rhythm Of Salsa.swiftpm/Resources/Assets.xcassets/Icons/$stem.imageset/$stem.pdf" "$path"
  fi
done
