#!/bin/bash

set -e
cd "$(dirname $0)/.."

for path in Icons/*; do
  name="$(basename "$path")"
  stem="${name%%.*}"
  inkscape -o "Introduction to Salsa.swiftpm/Resources/Assets.xcassets/Icons/$stem.imageset/$stem.pdf" "$path"
done
