name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build ${{ matrix.scheme }}
      run: xcodebuild -scheme "The Rhythm of Salsa" -destination "generic/platform=iOS"
      working-directory: The Rhythm Of Salsa.swiftpm
